version: '3.1'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure:5
    env_file: ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_HOST}

  mongo:
    image: mongo:latest
    restart: on-failure:5
    env_file: ./.env
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT_HOST}

  frontend:
    build:
      context: ./
      dockerfile: ./build/frontend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    restart: on-failure:5
    volumes:
      - ./Frontend:/app
    ports:
      - ${ANGULAR_PORT}:${ANGULAR_PORT_HOST}

  backend:
    build:
      context: ./
      dockerfile: ./build/asp/Dockerfile
    restart: on-failure:5
    volumes:
      - ./Backend/bin/Debug/net5.0:/app
    env_file: ./.env
    ports:
      - ${ASPNETCORE_PORT}:${ASPNETCORE_PORT_HOST}

  nginx:
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: on-failure:30
    ports:
      - 80:80
      - 443:443


volumes:
  postgres-data:
  mongo-data:
